#server:
#  port: 9002
#spring:   # 服务名称
#  application:
#    name: myshop-web
#  datasource:
#    url: jdbc:mysql://47.84.72.144:3307/springcloud?characterEncoding=UTF8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: helloworld
#  jpa:
#    show-sql: true # 是否打印sql语句
#    generate-ddl: true # 是否自动建表
#    database: mysql # jpa连接的数据库类型
#eureka:
#  client:
#    register-with-eureka: true # 作为客户端需要注册到Eureka
#    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
#    service-url: # 客户端注册地址
#      defaultZone: http://localhost:8888/eureka
#  instance:
#    # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
#    prefer-ip-address: true
#feign:
#  hystrix:
#    enabled: true
## 修改Ribbon的负载均衡算法
#myshop-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule