server:
  port: 9001
spring:
  application:
    name: myshop-user
  datasource:
    url: jdbc:mysql://47.84.72.144:3306/springcloud?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: members
    password: 3dhelloworld

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql