version: '3.7'
services:
  nacos:
    image: nacos/nacos-server:v2.1.1
    container_name: nacos-server
    environment:
      - MODE=standalone
      - _SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - LANG=zh_CN.UTF-8
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    volumes:
      - ./data/:/home/nacos/data
      - ./logs:/home/nacos/logs
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      network:
        ipv4_address: 172.20.0.3

  mysql:
    image: mysql:8.0
    container_name: nacos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data1:/var/lib/mysql
    restart: on-failure
    networks:
      network:
        ipv4_address: 172.20.0.2

  user-service:
    build:
      context: ./user-service
    depends_on:
      - nacos
      - mysql
      - common-utils
    deploy:
      replicas: 3
    networks:
      - network

  ocr-service:
    build:
      context: ./ocr-service
    depends_on:
      - nacos
      - mysql
      - common-utils
    deploy:
      replicas: 3
    networks:
      - network

  ocr-gateway:
    build:
      context: ./ocr-gateway
    ports:
      - "8087:8087"
    depends_on:
      - nacos
      - mysql
      - common-utils
    networks:
      - network

  common-utils:
    build:
      context: ./common-utils
    depends_on:
      - nacos
      - mysql
    networks:
      - network

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16