server:
  port: 12001
spring:
  application:
    name: myshop-config
  profiles:
    active: subversion
  rabbitmq:
    host: 47.84.72.144
    username: guest
    password: guest
  cloud:
    config:
      server:
        svn:
          uri: https://summer/svn/springcloud
          username: summer
          password: sxy2020##
          default-label: trunk
          search-paths: trunk

management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    regisiter-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true