#spring:
#  application:
#      name: myshop-web
##  cloud:
##    config:
##      uri: http://127.0.0.1:12000
##      profile: dev
##      name: myshop-web
##      label: main
#  rabbitmq:
#    host: 47.84.72.144
#    username: guest
#    password: guest
#server:
#    port: 9002
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8888/eureka
#  instance:
#    prefer-ip-address: true
#feign:
#    hystrix:
#        enabled: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - hystrix_stream
#          - bus_refresh
#
#  endpoint:
#    bus-refresh:
#      enabled: true
#
#
#
