spring:

  application:
    name: ocr-gateway

  #  main:
  #    web-application-type: reactive # 设为 'reactive' 来解决 Spring MVC 与 Spring Cloud Gateway 冲突
  main:
    web-application-type: reactive

  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 地址
        username: nacos
        password: nacos
        namespace: public
        group: ocr_back

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-route
          uri: lb://user-service # 负载均衡调用 user-service
          predicates:
            - Path=/user/** # 匹配路径 /user/**

        - id: ocr-service-route
          uri: lb://ocr-service # 负载均衡调用 ocr-service
          predicates:
            - Path=/ocr/** # 匹配路径 /ocr/**
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nacos
    username: nacos
    password: nacos



server:
  port: 8087

