spring:
  application:
      name: myshop-web


server:
    port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    prefer-ip-address: true
feign:
    hystrix:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream




